### ISSUE TITLE
leave certain tags untouched.

### ISSUE THREAD

**Issue by roni-estein** [shufo/prettier-plugin-blade#114]
Is it possible to leave the contents of certain tags untouched? Like long SVG tags with multiple attributes?

**Comment by shufo** [comment]
Currently there is no option to not format only certain tags. 

[Disabling format](https://github.com/shufo/prettier-plugin-blade#disabling-format-in-file) or using `.prettierignore` may work for you.
or specify `preserve` with wrapAttributes option will preserve attributes.
