### ISSUE TITLE
Empty lines

### ISSUE THREAD

**Issue by jeanvcastro** [shufo/prettier-plugin-blade#127]
The plugin does not collapse multiple blank lines into a single blank line.

It would be great if it supported this like other parsers.

**Comment by shufo** [comment]
Hi @jeanvcastro 
Currently working on this feature at https://github.com/shufo/blade-formatter/issues/657
I'll include this feature soon.

**Comment by jeanvcastro** [comment]
Nice!

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/prettier-plugin-blade/releases/tag/v1.5.0
