### ISSUE TITLE
Invalid quote type used in @php block

### ISSUE THREAD

**Issue by mortenscheel** [shufo/prettier-plugin-blade#138]
This is kind of an edge case, but I'll mention it anyway.

### Input
```blade
@php
$icon = "<i class='fa fa-check'></i>";
@endphp
```
### Output
```blade
@php
$icon = '<i class='fa fa-check'></i>';
@endphp
```

Apparently this only happens with html strings in double quotes inside @php blocks. Which I'll admit is a weird thing to have in a blade file, but I didn't know that at the time.

**Comment by shufo** [comment]
Thanks @mortenscheel 
Fixed at https://github.com/shufo/prettier-plugin-blade/releases/tag/v1.5.6

**Comment by mortenscheel** [comment]
Thanks for the quick fix.
Impressive project by the way. I like the design.
