### ISSUE TITLE
[feature request] Combination of auto and force-expand-multiline for wrapAttributes option

### ISSUE THREAD

**Issue by Thomva** [shufo/prettier-plugin-blade#144]
Hi, I would love to see a combination of `auto` and `force-expand-multiline` for the `wrapAttributes` option.

So, `force-expand-multiline` if the `printWidth` is exceeded, else put them on a single line.

Is this possible already? Or can someone add this option? Thanks!

**Comment by shufo** [comment]
Hi @Thomva.
Currently there is no option to combine that two options. It follows https://github.com/beautify-web/js-beautify 's wrap attributes rule.
I think `preserve` or `preserve-aligned` is close to a combination of the two.
