### ISSUE TITLE
Parse only blade files. Ignore other .php files

### ISSUE THREAD

**Issue by mpont91** [shufo/prettier-plugin-blade#149]
Hi there,

I thought this plugin would only parse .*blade.php files but it also does with all *.php files.

It is possible to only parse blade files? For the basic PHP I've already have laravel-pint.

**Comment by shufo** [comment]
HI @mpont91 
It might depends on how you specify files in arguments.

Using wildcard like belog would only lookup `*.blade.php`

```bash
$ ./node_modules/.bin/prettier resources/**/*.blade.php
```
