### ISSUE TITLE
Formatting stops working when inline @php directive present in tag

### ISSUE THREAD

**Issue by holaontiveros** [shufo/prettier-plugin-blade#156]
Hi, thanks a lot for the plugin just wanted to report a possible bug

When having something like: 

```blade
<article @php(post_class('lg:pt-10'))>
            <header class=" px-0 lg:px-4 container"></header>
</article>
```

the code get's formated to:

```blade
<article
    @php(post_class('lg:pt-10'))>
            <header class=" px-0 lg:px-4 container"></header>
</article>
```

if the `@php` inline directive is remove or changed to `@php @endphp` the formatting works as expected.

This includes all types of formatting, including the tailwind sorting that made me realize my file was being formatted as expected

**Comment by CalebDW** [comment]
Note that Laravel has deprecated the inline `@php()` directive:

https://github.com/laravel/framework/pull/48420#issuecomment-1739237112
