### ISSUE TITLE
multiple blade directives on one line

### ISSUE THREAD

**Issue by Polfo** [shufo/prettier-plugin-blade#18]
I try to combine this with `prettier-plugin-tailwindcss` which is not blade aware and sometimes puts some @ directives on one line.
For the following cases, `prettier-plugin-blade` keeps them on one line, causing layout issues, while it is solved if I separatly split these in two lines before having `prettier-plugin-blade` process the file . Could `prettier-plugin-blade` do that split in two lines for us?
```
@endcan @if
@switch($choice) @case('projects')
@break @case('project')
@break @default
@endcan @if ($condition)
```

**Comment by shufo** [comment]
Hi @Polfo . Thank for trying out and for your feedback!
Unfortunately currently this plugin does not resolve per directive line break automatically. 
So it is recommended to insert line breaks as much as possible, even if it is rough.

e.g.

```blade
@switch($choice) 
@case('projects')
foo
@break 
@case('project')
bar
@break 
@default
baz
@endswitch
```

will format into

```blade
    @switch($choice)
        @case('projects')
            foo
        @break
        @case('project')
            bar
        @break
        @default
            baz
    @endswitch
```

**Comment by shufo** [comment]
I'll look into the automatic line breaks for each directive. Thank you.

**Comment by Polfo** [comment]
https://github.com/shufo/blade-formatter/pull/474 is an improvement indeed. It would be nice if also these cases could be handled:

    @switch($type) @case(1) $a = 3; @break @case(2) @case(3) $a = 4; @break @default $a = null; @endswitch

and 

    @can('can') $a = 1; @endcan @if (true) $a = 1; @else $a = 2; @endif

They currently result in 

    @switch($type)
        @case(1) $a = 3; @break @case(2)
            @case(3) $a = 4; @break @default $a = null;
        @endswitch

and

    @can('can')
        $a = 1;
        @endcan @if (true)
        $a = 1; @else $a = 2;
        @endif

**Comment by Polfo** [comment]
Since prettier-plugin-tailwindcss is now integrated, this is not an issue any more.
Thanks for the great job.
