### ISSUE TITLE
[Formatting Bug]: does not format when inline directive and if directive mixed

### ISSUE THREAD

**Issue by theMosaad** [shufo/prettier-plugin-blade#199]
### Version

1.8.12

### Template before formatting

```blade
<div @php($counter = 1) >
     <x-share>
    @if ($counter)
          {{--  --}}
    @endif
  </x-share>
</div>
```

### Template after formatting

```blade
<div
  @php($counter = 1) >
     <x-share>
    @if ($counter)
          {{--  --}}
    @endif
  </x-share>
</div>
```

### Expected

-  `@php($counter = 1)` not to wrap and stay in the same line like `<div @php($counter = 1) >`.
- `<x-share>` to have the same indent as `</x-share>`.
- the space between `@php($counter = 1)` and the closing bracket `>` to be removed.

### Config
This test is done with a fresh Prettier VSCode plugin & no config rules aside from the essential to make this plugin work:

```
{
  "plugins": ["@shufo/prettier-plugin-blade"],
  "overrides": [
    {
      "files": ["*.blade.php"],
      "options": {
        "parser": "blade"
      }
    }
  ]
}
```

### Workarounds

1. replacing `@php($counter = 1)` with `@php $counter = 1 @endphp`.
2. remove the `@if` statement inside the `x-share` component.

### Relevant log output

```blade
<div @php($counter = 1) >
        <x-share>
    @if ($counter)
       {{--  --}}
    @endif
    </x-share>
</div>
```

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/prettier-plugin-blade/releases/tag/v1.13.4.
Thanks for your patience!
