### ISSUE TITLE
[Bug]: Error [ERR_REQUIRE_ESM] with "sortTailwindcssClasses"

### ISSUE THREAD

**Issue by IdrisN** [shufo/prettier-plugin-blade#203]
### Description

Setting "sortTailwindcssClasses" to true results to the following error:
```
["ERROR" - 12:29:07] Error formatting document.
["ERROR" - 12:29:07] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/idrisn/dev/todolu/tailwind.config.js from /Users/idrisn/dev/todolu/node_modules/@shufo/tailwindcss-class-sorter/dist/main.js not supported.
Instead change the require of tailwind.config.js in /Users/idrisn/dev/todolu/node_modules/@shufo/tailwindcss-class-sorter/dist/main.js to a dynamic import() which is available in all CommonJS modules.
Error: Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/idrisn/dev/todolu/tailwind.config.js from /Users/idrisn/dev/todolu/node_modules/@shufo/tailwindcss-class-sorter/dist/main.js not supported.
Instead change the require of tailwind.config.js in /Users/idrisn/dev/todolu/node_modules/@shufo/tailwindcss-class-sorter/dist/main.js to a dynamic import() which is available in all CommonJS modules.
    at /Users/idrisn/dev/todolu/node_modules/blade-formatter/dist/bundle.js:59:2579
    at async /Users/idrisn/dev/todolu/node_modules/@shufo/prettier-plugin-blade/src/worker.js:5:18
["INFO" - 12:29:07] Formatting completed in 22ms.
```

### Expected Behavior

```blade
<form action="#" class="relative">
    <div class="text-xs flex p-6 ">
        Test
    </div>
</form>

```
This test file should be sorted correctly.

### Actual Behavior

The formatter fails and stops with the error mentioned above.

### Additional Context

"prettier": "2.8.8",
"tailwindcss": "3.3.2",
"@shufo/prettier-plugin-blade": "^1.8.13",

```
# .prettierrc
{
    "plugins": ["@shufo/prettier-plugin-blade"],
    "overrides": [
        {
            "files": ["*.blade.php"],
            "options": {
                "parser": "blade",
                "tabWidth": 4,
                "sortTailwindcssClasses": true,
                "wrapAttributes": "auto"
            }
        }
    ]
}


```

**Comment by shufo** [comment]
It seems ESM setting used in your project causes this error.
Currently `@shufo/prettier-plugin-blade` does not support ESM so it could not read `tailwind.config.js`.

For work around, you can use CommonJS style config for `tailwind.config.js`

Delete type module setting from `package.json`

```diff
-"type": "module"
```

`tailwind.config.js`

e.g.

```js
const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
    theme: {
        screens: {
            sm: "0",
            md: "834px",
            lg: "1024px",
            xl: "1200px",
            xxl: "1440px",
            xxxl: "1900px",
            ...defaultTheme.screens,
        },
    },
};
```

But I'll consider dual support for ESM and CommonJS. Thanks @IdrisN

**Comment by jahvi** [comment]
@shufo This sort of works but Laravel vite expects the file to be an ESM module so making this change makes "npm run dev" break. I'm using VS Code so I could use this workaround instead:

1. Do the steps above and restart VS Code
2. Undo the changes above, somehow VS Code still "remembers" the previous changes so sorting works and running npm commands as well. (At least until it's restarted again)

Might be worth moving to ESM even with a major version bump seem that seems the direction most JS packages are going.

**Comment by shufo** [comment]
@jahvi 
Yes, I'm now working on ESM support.
https://github.com/shufo/blade-formatter/issues/820#issuecomment-1614132967
It depends on some CJS package so I must upgrade dependency packages first.
It might take about 1~2 weeks.

>Undo the changes above, somehow VS Code still "remembers" 

I also had that weird VSCode behaviour in past. Probably VSCode caches configs reading from this package.
I too restarting the VSCode is the only workaround.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/prettier-plugin-blade/releases/tag/v1.9.1.
Please try upgrade to `^1.9,0`.

**Comment by jahvi** [comment]
Getting the following error when trying to format a blade file:

```
Error: Unknown node type: undefined
    at Object.p [as print] (/doc/node_modules/@shufo/prettier-plugin-blade/src/options.ts:3:3)
    at callPluginPrintFunction (/doc/node_modules/prettier/index.js:8601:26)
    at mainPrintInternal (/doc/node_modules/prettier/index.js:8550:22)
    at mainPrint (/doc/node_modules/prettier/index.js:8537:18)
    at printAstToDoc (/doc/node_modules/prettier/index.js:8529:18)
    at coreFormat (/doc/node_modules/prettier/index.js:8837:20)
    at formatWithCursor2 (/doc/node_modules/prettier/index.js:9021:18)
    at /doc/node_modules/prettier/index.js:38183:12
    at Object.format (/doc/node_modules/prettier/index.js:38197:12)
    at t.PrettierMainThreadInstance.format (/live/.vscode/extensions/esbenp.prettier-vscode-9.19.0/dist/extension.js:1:18023)
    at t.default.format (/live/.vscode/extensions/esbenp.prettier-vscode-9.19.0/dist/extension.js:1:16114)
    at t.PrettierEditProvider.provideEdits (/live/.vscode/extensions/esbenp.prettier-vscode-9.19.0/dist/extension.js:1:12672)
    at U.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:45790)
```

File:

```
<div class="flex">asd</div>
```

Version: 1.9.1
Node: 18.12
Prettier: 2.8.8

**Comment by shufo** [comment]
@jahvi 
Thanks for trying upgrade.
From 1.9.0, `@shufo/prettier-plugin-blade` depends on Prettier >= 3.0 so can you try upgrade prettier to ^3.0? 
Prettier introduces breaking change between 2.0 and 3.0.


```bash
$ npm install -g prettier@3.0.0
```

or it's better to use local dependencies cause it can enclose the dependencies.

```bash
$ cd your_project
$ npm install --save-dev prettier @shufo/prettier-plugin-blade 
# yarn add -D prettier @shufo/prettier-plugin-blade
$ ./node_modules/.bin/prettier ~~~
```
