### ISSUE TITLE
[Formatting Bug]: if else endif removes the trailing space inline and breaks the blade

### ISSUE THREAD

**Issue by tonypartridge** [shufo/prettier-plugin-blade#204]
### Version

1.5.6

### Template before formatting

```blade
class="@if(amount > 0) py-2 @else py-4 px-4 @endif relative"
```

### Template after formatting

```blade
class="@if($amount > 0) py-2 @else py-4 px-4 @endifrelative"
```

### Expected Behaviour

class="@if($amount > 0) py-2 @else py-4 px-4 @endif relative"

**Comment by aryala7** [comment]
i also have this issue. 
this is my config file
`{
    "useLaravelPint": true,
    "classStrings": {
        "enabled": false
    },
    "pintCacheEnabled": false,
    "customIfs": [],
    "formatDirectivePhpParameters": false,
    "formatDirectiveJsonParameters": false,
    "formatInsideEcho": false,
    "spacesAfterDirective": 1,
    "spacesAfterControlDirective": 3,
    "phpOptions": {
        "phpVersion": "8.2"
    }
}
`
before formatting:
`@if((isset($banner) && $banner->model_type === 0) || old('model_type') === 0) selected @endif  value=""`

after formatting:
`@if((isset($banner) && $banner->model_type === 0) || old('model_type') === 0) selected @endifvalue=""`

**Comment by shufo** [comment]
@aryala7 
Seems this config is not for this package.

```json
{
  "useLaravelPint": true,
  "classStrings": {
    "enabled": false
  },
  "pintCacheEnabled": false,
  "customIfs": [],
  "formatDirectivePhpParameters": false,
  "formatDirectiveJsonParameters": false,
  "formatInsideEcho": false,
  "spacesAfterDirective": 1,
  "spacesAfterControlDirective": 3,
  "phpOptions": {
    "phpVersion": "8.2"
  }
}

```

Please paste entire template (remove secret value if needed) and config cause I could not reproduce it.

**Comment by Swennet** [comment]
To anyone reading this, I experienced the same issue in PHPStorm, and excluding PHPStorm's default blade formatting fixed this issue for me.

It looks like this is not an issue with the prettier-plugin-blade package.

To disable default blade formatting, go to Editor -> Code Style and add `*.blade.php` to "Do not format".
