### ISSUE TITLE
[Bug]:  1.9.* Breaks formatting in Nova ( from Panic )

### ISSUE THREAD

**Issue by yabdab** [shufo/prettier-plugin-blade#210]
### Description

Not sure if this has to do with the Prettier extension in Nova, but when updating prettier-plugin-blade passed 1.8.13 all formatting breaks. No error messages, but the formatting on blade does nothing.

Anyone else?

### Expected Behavior

Format blade files.

### Actual Behavior

Does not format blade files .

**Comment by shufo** [comment]
@yabdab 
Is the version of the pretier used in the format command 3.0?
If it is 2.0, an error will occur.
https://github.com/shufo/prettier-plugin-blade/issues/203#issuecomment-1622910881

**Comment by yabdab** [comment]
Pretty sure the Prettier Extension uses 2.0 still. Maybe that is the problem?

I may just lock in 1.18.3 since it works great as is.

**Comment by shufo** [comment]
@yabdab 
Please try upgrade Prettier to 3.0.

```
$ npm install -g prettier@3.0.0
```

or use local dependencies

```
$ cd your_project
$ npm install --save-dev prettier @shufo/prettier-plugin-blade 
# yarn add -D prettier @shufo/prettier-plugin-blade
$ ./node_modules/.bin/prettier ~~~
```
