### ISSUE TITLE
[Formatting Bug]: Does not respect prettier bracketSameLine

### ISSUE THREAD

**Issue by calebdw** [shufo/prettier-plugin-blade#218]
### Version

1.10.0

### Template before formatting

```blade
@section('buttons')
    <x-button.nav
        :href="route('eaglesys::warehouse.create')"
        image="page_add"
        label="Add New Warehouse"
    />
@endsection
```

### Template after formatting

```blade
@section('buttons')
    <x-button.nav :href="route('eaglesys::warehouse.create')"
        image="page_add"
        label="Add New Warehouse" />
@endsection
```

### Expected Behaviour

Hello!

I want to use the `wrapArrtibutes: 'force'` option, however, I don't want it to place the bracket on the same line as the last attribute (note that the [default behaviour](https://prettier.io/docs/en/options.html#bracket-line
) in prettier is to place the bracket on the next line). I tried adding an `bracketSameLine: false` override, but it does not seem to be respected

Thanks!

`.prettierrc.json`
```json
{
    "plugins": [
        "@shufo/prettier-plugin-blade"
    ],
    "overrides": [
        {
            "files": [
                "*.blade.php"
            ],
            "options": {
                "bracketSameLine": false,
                "parser": "blade",
                "printWidth": 80,
                "sortTailwindcssClasses": true,
                "tabWidth": 4,
                "wrapAttributes": "force"
            }
        }
    ]
}
```

**Comment by francoism90** [comment]
Same here, any solution/workaround? :)

**Comment by pindab0ter** [comment]
I would love to see this issue fixed.
