### ISSUE TITLE
[Bug]: In doc is missing --end-with-new-line in .prettierrc example

### ISSUE THREAD

**Issue by dbursa** [shufo/prettier-plugin-blade#236]
### Description

I tried `endWithNewLine: false`, but its not working. Can you provide correct name?

### Expected Behavior

In .prettierrc with `endWithNewLine: false` shloud not to end with new line

### Actual Behavior

With `endWithNewLine: false` nothing happen

### Additional Context

prettier: 3.0.3
@shufo/prettier-plugin-blade: 1.11.1

**Comment by dbursa** [comment]
@shufo  i found in code it should be `endWithNewline` (with small l in line). But still doesn't work? What should do this feature? Can you provide any example pls?

**Comment by OreQr** [comment]
endWithNewLine feature doesn't work
