### ISSUE TITLE
[Formatting Bug]: Adds spaces where there shouldn't be

### ISSUE THREAD

**Issue by CalebDW** [shufo/prettier-plugin-blade#239]
### Version

1.11.1

### Template before formatting

```blade
@php
    use Eagle\Utilities\Dates\TimeZone;
<- no spaces here
    $timezone_options =
        ['' => ''] +
        TimeZone::create()
            ->format('tz-label')
            ->countryCodePriority('US')
            ->get();
@endphp
```

### Template after formatting

```blade
@php
    use Eagle\Utilities\Dates\TimeZone;
    <- four spaces here
    $timezone_options =
        ['' => ''] +
        TimeZone::create()
            ->format('tz-label')
            ->countryCodePriority('US')
            ->get();
@endphp
```

### Expected Behaviour

The formatter shouldn't input spaces where there should just be a newline char---some editors show these whitespace characters and remove them automatically:

![image](https://github.com/shufo/prettier-plugin-blade/assets/4176520/a255a580-7429-4773-814b-44029d775d78)

Note that this only applies to extra spaces at the end of the line

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/prettier-plugin-blade/releases/tag/v1.13.1.
Thank you @CalebDW!
