### ISSUE TITLE
Usage in combination with Tailwind CSS Prettier Plugin

### ISSUE THREAD

**Issue by Wulfheart** [shufo/prettier-plugin-blade#24]
Is it possible to run it with the Tailwind CSS Prettier Plugin? I installed it alongside this package and it is not working.

I would expect it to properly sort the classes when both plugins are installed.

```html
<div class="white px-4 sm:px-8 py-2 sm:py-3 bg-sky-700 hover:bg-sky-800">
</div>
```

**Comment by shufo** [comment]
@Wulfheart 
Unfortunately, the Tailwind CSS Prettier Plugin doesn't support blade, so it might be a bit tricky to integrate with this plugin with Official Tailwind CSS Prettier plugin.
https://github.com/shufo/prettier-plugin-blade/issues/18#issuecomment-1036044040

There is a solution for sorting Tailwind CSS classes that you might use.

- https://marketplace.visualstudio.com/items?itemName=heybourn.headwind (VSCode exxtension)
- https://github.com/avencera/rustywind (CLI version of headwind)

However, I know there's a demand for integration with the Tailwind CSS Plugin, so I'll look into it!

**Comment by Wulfheart** [comment]
Maybe you could team up with @ryangjchandler who is currently developing https://github.com/ryangjchandler/prettier-plugin-blade.

**Comment by ryangjchandler** [comment]
Our plugin uses the TW plugin's HTML formatter so it works out of the box.

**Comment by shufo** [comment]
@Wulfheart 
Added Tailwind CSS class sorting feature at https://github.com/shufo/prettier-plugin-blade/releases/tag/v1.1.0

PR:
https://github.com/shufo/prettier-plugin-blade/pull/26#issue-1152960473
