### ISSUE TITLE
[Bug]: Install command is installing prettier v2.8.8

### ISSUE THREAD

**Issue by ryanmortier** [shufo/prettier-plugin-blade#257]
### Description

This is the weirdest thing and I have no idea if this is a bug with `npm` or this repo's dependencies or something and this seems like it might be related to #230.

If you install this plugin with the following command `npm install --save-dev @shufo/prettier-plugin-blade prettier` as listed on the readme, then prettier v2.8.8 is installed for some reason. I've reproduced this in fresh new projects.

Steps to reproduce:

Here is a new project with nothing installed via npm (`nls` is aliased to `npm list --depth=0`):

```
➜ nls
laravel@ /Users/ryan/Code/laravel
└── (empty)
```
```
➜ npm install --save-dev @shufo/prettier-plugin-blade prettier

added 184 packages, and audited 185 packages in 4s

37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```
➜ nls
laravel@ /Users/ryan/Code/laravel
├── @shufo/prettier-plugin-blade@1.13.4
└── prettier@2.8.8
```
```
➜ npm uninstall @shufo/prettier-plugin-blade prettier

removed 184 packages, and audited 1 package in 528ms

found 0 vulnerabilities
```
```
➜ nls
laravel@ /Users/ryan/Code/laravel
└── (empty)
```
```
➜ npm install --save-dev prettier

added 1 package, and audited 2 packages in 303ms

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```
➜ nls
laravel@ /Users/ryan/Code/laravel
└── prettier@3.1.0
```
```
➜ npm install --save-dev @shufo/prettier-plugin-blade

added 184 packages, and audited 186 packages in 3s

38 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```
➜ nls
laravel@ /Users/ryan/Code/laravel
├── @shufo/prettier-plugin-blade@1.13.4
└── prettier@3.1.0
```

Also, it doesn't matter if I install this plugin first or prettier first, as long as I install one at a time, I get `prettier@3.1.0`. If both are in the same line during install, I get `prettier@2.8.8`.

### Expected Behavior

Should install `prettier@3.1.0`.

### Actual Behavior

Installs `prettier@2.8.8`.

### Additional Context

node v21.3.0
npm v10.2.4

**Comment by shufo** [comment]
Sorry for delay, now working on upgrade to prettier to v3!
