### ISSUE TITLE
[Formatting Bug]: Indentation gets removed in @php blocks in blade files since v1.13

### ISSUE THREAD

**Issue by plorenz-etes** [shufo/prettier-plugin-blade#266]
### Version

1.13.5

### Template before formatting

```blade
<html>
  <head></head>
  <body>
    @php
      $categories = App\Models\Category::whereIn('id', $catids)
        ->orderBy('description')
        ->get();
    @endphp
  </body>
</html>
```

### Template after formatting

```blade
<html>
  <head></head>
  <body>
    @php
      $categories = App\Models\Category::whereIn('id', $catids)->orderBy('description')->get();
    @endphp
  </body>
</html>
```

### Expected Behaviour

The indented function calls (query builder) should remain as-is. This was working correctly with 1.12.

**Comment by claytonrcarter** [comment]
I see the same thing, but I think that this is an issue w/ `blade-formatter`, not this plugin specifically. 1.12 was using `blade-formatter` 1.38, while 1.13 is using 1.40. Sure enough, the standalone `blade-formatter` puts this all on one line when using 1.40, but not when using 1.38.

**Comment by Orrison** [comment]
Seeing this same issue
