### ISSUE TITLE
[Bug]: After update to Prettier v3 VSCode stopped recognizing blade formatter

### ISSUE THREAD

**Issue by MartinPL** [shufo/prettier-plugin-blade#274]
### Description

 After package update to 1.14.1 & prettier 3.2.5 VSCode stopped recognizing blade formatter. Formatting on save stopped working

### Expected Behavior

In v2 version I could format blade file on save or using command "Format Document".

### Actual Behavior

Only one method of formatting works - "Format Document (Force)". Formatting on save don't work, "Format Docuemnt" returns "There is no formatter for 'blade' files installed."

### Additional Context

Maybe related tasks https://github.com/prettier/prettier/issues/13729?

**Comment by MartinPL** [comment]
Just to confirm, after downgrading all works fine:
"@shufo/prettier-plugin-blade": "1.8.9",
"prettier": "2.8.0",

**Comment by shufo** [comment]
Thank you @MartinPL 
I'll look into it.

**Comment by martinpl** [comment]
Yep looks like this issue was fixed in meantime: 
I only needed 
```
"[blade]": {
  "editor.defaultFormatter": "esbenp.prettier-vscode"
},
```

and Laravel official extensions for separating blade.php from regular php
