### ISSUE TITLE
[Formatting Bug]: custom directives support?

### ISSUE THREAD

**Issue by kukac7** [shufo/prettier-plugin-blade#289]
### Version

latest

### Template before formatting

```blade
@hasfield('list')
  <ul>
    @fields('list')
      <li>@sub('item')</li>
    @endfields
  </ul>
@endfield
```

### Template after formatting

```blade
Error formatting document.
```

### Expected Behaviour

hi,

is it possible to somehow increase the number of supported directives?
it seems that the https://github.com/log1x/sage-directives composer package is not supported.
it says an error when formatting: `Error formatting document.`

thanks for the help!

**Comment by shufo** [comment]
Currently supported custom directive format is `@~~~` with `@end~~~`. (~~~ must matched with start and end directive)

If sage-directive's `@endfield` was `@endhasfield`, it works as expected.

```blade
@hasfield('list')
  <ul>
    @fields('list')
      <li>@sub('item')</li>
    @endfields
  </ul>
@endhasfield
```
