### ISSUE TITLE
Tailwind CSS sorting with custom values does not seem to work

### ISSUE THREAD

**Issue by eronisko** [shufo/prettier-plugin-blade#33]
Thanks so much for this plugin. I've noticed that the Tailwind CSS class sorting does not seem to work when there's a custom value in the class list. In fact the formatter seems to "give up" on the class attribute entirely

E.g.:
```html
<div class="md:tw-mx-[1rem]   tw-mx-1"></div>
```

Expected result:
```html
<div class="tw-mx-1 md:tw-mx-[1rem]"></div>
```

Actual result:
```html
<div class="md:tw-mx-[1rem]   tw-mx-1"></div>
```

**Comment by shufo** [comment]
Hi @eronisko. 
Thanks for reporting the issue and examples!

Probably this is a problem with the sorting.
I'll take a look into it.

**Comment by shufo** [comment]
Fixed at https://github.com/shufo/prettier-plugin-blade/releases/tag/v1.1.7

**Comment by eronisko** [comment]
Thanks for the fast resolution!
