### ISSUE TITLE
add bracketSameLine as an option?

### ISSUE THREAD

**Issue by yabdab** [shufo/prettier-plugin-blade#59]
Any chance you could add bracketSameLine as one of the config options?

**Comment by shufo** [comment]
Hi @yabdab.
Thanks for suggestion. 

Currently `bracketSameLine` is not supported but a similar behavior could be done by setting the wrap attributes option to `force-aligned`.

```js
❯ cat .prettierrc.json
{
    "wrapAttributes": "force-aligned"
}
```

```blade
<div id="foo-bar-baz" class="bar-foo-baz" title="a sample title" data-foo="bar" data-bar="baz">
  lorem ipsum dolor sit amet
</div>
```

will format into

```blade
<div id="foo-bar-baz"
     class="bar-foo-baz"
     title="a sample title"
     data-foo="bar"
     data-bar="baz">
    lorem ipsum dolor sit amet
</div>
```

This behavior is almost the same with Prettier default `bracketSameLine`, except that the first line attribute does not break the line.

So if a `bracketSameLine` is specified by config, it might be good to interpret the `wrapAttributes` as being specified as `force-aligned`.

I'll consider the behavior about it, thanks.

**Comment by yabdab** [comment]
I did that, yet I am still getting this result...

```html
 <svg
            class="h-4 w-4"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="currentColor"
            aria-hidden="true"
          >
            <path
              fill-rule="evenodd"
              d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
              clip-rule="evenodd"
            />
          </svg>
```
