### ISSUE TITLE
Getting `Cannot find module '@shufo/prettier-plugin-blade'` when using VS Code

### ISSUE THREAD

**Issue by Bassadin** [shufo/prettier-plugin-blade#81]
Hi,

when I try to format my blade files with VS Code while having the plugin installed via npm and set in the plugins array in my `.prettierrc`, I get the error `Cannot find module '@shufo/prettier-plugin-blade'`.

I'm using:

- `"prettier": "2.6.2"`
- `"@shufo/prettier-plugin-blade": "^1.4",`
- VS Code Prettier plugin: v9.5.0
- Windows 10

I also trie setting the `prettier.resolveGlobalModules` setting to true, to no avail.

I hope that's plenty into, feel free to ask for more :)

Full error log:

```
["ERROR" - 10:47:57] Error formatting document.
["ERROR" - 10:47:57] Cannot find module '@shufo/prettier-plugin-blade'
Require stack:
- c:\Users\abc\Documents\Git-Repos\XYZ\forensic-ai-web\node_modules\prettier\index.js
- c:\Users\abc\.vscode\extensions\esbenp.prettier-vscode-9.5.0\dist\extension.js
- c:\Users\abc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\abc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\abc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
Error: Cannot find module '@shufo/prettier-plugin-blade'
Require stack:
- c:\Users\abc\Documents\Git-Repos\XYZ\forensic-ai-web\node_modules\prettier\index.js
- c:\Users\abc\.vscode\extensions\esbenp.prettier-vscode-9.5.0\dist\extension.js
- c:\Users\abc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\abc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\abc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
    at h.resolve (c:\Users\abc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:761)
    at c:\Users\abc\Documents\Git-Repos\XYZ\forensic-ai-web\node_modules\prettier\index.js:39110:25
    at Array.map (<anonymous>)
    at Object.load (c:\Users\abc\Documents\Git-Repos\XYZ\forensic-ai-web\node_modules\prettier\index.js:39105:65)
    at Object.load [as loadPlugins] (c:\Users\abc\Documents\Git-Repos\XYZ\forensic-ai-web\node_modules\prettier\index.js:15998:27)
    at c:\Users\abc\Documents\Git-Repos\XYZ\forensic-ai-web\node_modules\prettier\index.js:39172:24
    at Object.Success [as format] (c:\Users\abc\Documents\Git-Repos\XYZ\forensic-ai-web\node_modules\prettier\index.js:39188:12)
    at t.default.format (c:\Users\abc\.vscode\extensions\esbenp.prettier-vscode-9.5.0\src\PrettierEditService.ts:463:45)
    at t.PrettierEditProvider.provideEdits (c:\Users\abc\.vscode\extensions\esbenp.prettier-vscode-9.5.0\src\PrettierEditService.ts:322:22)
    at z.provideDocumentFormattingEdits (c:\Users\abc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:105121)
```

**Comment by shufo** [comment]
Thanks @Bassadin 

It seems to work when I remove the `plugins` description in `.prettierrc`.

```diff
{
-   "plugins": ["@shufo/prettier-plugin-blade"]
}
```

I've added the description of the `plugins` to README in this [PR](https://github.com/shufo/prettier-plugin-blade/pull/42), but maybe that's results in unexpected side effect.

**Comment by Waghabond** [comment]
Its very strange, in my own evironment, just giving my experience. 
For some reason the CLI command and extension seemed to not "work". However if I added `"plugins": ["@shufo/prettier-plugin-blade"]` into my `.prettierrc` the CLI command began to work/format the blade files correctly. But adding that line also broke the vscode extension and it kept giving Cannot find module '@shufo/prettier-plugin-blade'. 

In the end the fix was to remove the plugins line and explicitly specify the parser for blade files. 
```diff
-  "plugins": ["@shufo/prettier-plugin-blade"],
   "wrapAttributes": "force-aligned",
   "overrides": [
       {
           "files": ["*.blade.php"],
           "options": {
               "tabWidth": 2,
+              "parser": "blade",
           },
       },
   ],
```
Perhaps this could be added into the troubleshooting section of the README as an option for people to try before attempting to add `"plugins": ["@shufo/prettier-plugin-blade"],` into `.prettierrc`

**Comment by Bassadin** [comment]
This seems to work for me as well! Seems a little weird to me, though.

**Comment by Blinks44** [comment]
Very strange, but removing ```"plugins": ["@shufo/prettier-plugin-blade"]``` brokes PHPStorm's prettier plugin to work with blade-prettier, if you're using PHPStorm, you have to remain this line in .prettierrc

**Comment by Waghabond** [comment]
@Blinks44 did you add the `"parser": "blade"`, when you removed the `"plugins": ["@shufo/prettier-plugin-blade"]` line? If yes, then the fact that it stopped working is probably just some difference between the vscode and phpstorm prettier extensions
